// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Nlxm_cLUJWTc93_1H4ps4N0wfNLMCD8',
    appId: '1:491982534039:web:7dd41c6fd652c40c5b00d2',
    messagingSenderId: '491982534039',
    projectId: 'scoutingapp-backend',
    authDomain: 'scoutingapp-backend.firebaseapp.com',
    storageBucket: 'scoutingapp-backend.appspot.com',
    measurementId: 'G-8MLXVBHJ2S',
    databaseURL: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrMN5J-rj2HU5AnwCUfNBFrBqZBqELlc',
    appId: '1:491982534039:android:06fee94a7b846e4b5b00d2',
    messagingSenderId: '491982534039',
    projectId: 'scoutingapp-backend',
    storageBucket: 'scoutingapp-backend.appspot.com',
    databaseURL: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OQhsgoNpEMnywCGLBLYXMnUekKrK4_o',
    appId: '1:491982534039:ios:2a704731411caaac5b00d2',
    messagingSenderId: '491982534039',
    projectId: 'scoutingapp-backend',
    storageBucket: 'scoutingapp-backend.appspot.com',
    iosBundleId: 'com.example.scoutingapp',
    databaseURL: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OQhsgoNpEMnywCGLBLYXMnUekKrK4_o',
    appId: '1:491982534039:ios:36591a50d8b21bc45b00d2',
    messagingSenderId: '491982534039',
    projectId: 'scoutingapp-backend',
    storageBucket: 'scoutingapp-backend.appspot.com',
    iosBundleId: 'com.example.scoutingapp.RunnerTests',
    databaseURL: '',
  );
}
